apiVersion: v1
kind: Service
metadata:
  name: api-prediction-svc
  labels:
    app: api_prediction
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: api_prediction